// export const imageSlide = [
//   {
//     url: "pic1.jpg",
//     title: "Woodwind accesories",
//     body: "Moutpieces, reeds",
//   },
//   {
//     url: "pic2.jpg",
//     title: "Instruments",
//     body: "Yamaha-Buffet ",
//   },
//   {
//     url: "pic3.jpg",
//     title: "Brass accesories",
//     body: "Mouthpieces, booster ",
//   },
//   {
//     url: "pic4.jpg",
//     title: "Strings",
//     body: "Instruments and accesories",
//   },
// ];

export const clarinet_accesories = [
  {
    id: "1",
    url: "pic-1.jpg",
    name: "Pomarico Saphire A/Bb Mouthpiece",
    price: 200,
    fabrication: "Italy",
    tags: ["Mouthpiece", "Crystal", "Pomarico", "BflatClarinet", "AClarinet"],
    group: "clarinet",
  },
  {
    id: "2",
    url: "pic-2.jpg",
    name: "Legere Reed Signature European Cut 2.5 ",
    price: 30,
    fabrication: "US",
    tags: ["Reed", "Synthetic", "Legere", "BflatClarinet", "AClarinet"],
    group: "clarinet",
  },
  {
    id: "3",
    url: "pic-3.jpg",
    name: "Silverstein Ligature Q07A",
    price: 80,
    fabrication: "US",
    tags: ["Ligature", "Silverstein", "BflatClarinet", "AClarinet"],
    group: "clarinet",
  },
  {
    id: "4",
    url: "pic-4.jpg",
    name: "Vandoren MouthPiece CM308 Traditional B45 ",
    price: 100,
    fabrication: "US",
    tags: ["Mouthpiece", "Ebonite", "Vandoren", "BflatClarinet", "AClarinet"],
    group: "clarinet",
  },
  {
    id: "5",
    url: "pic-5.jpg",
    name: "Vandoren Ligature LC21P",
    price: 80,
    fabrication: "US",
    tags: ["Ligature", "Vandoren", "BflatClarinet", "AClarinet"],
    group: "clarinet",
  },
  {
    id: "6",
    url: "pic-6.jpg",
    name: "Stand K&M 15222",
    price: 50,
    fabrication: "germany",
    tags: ["Stand", "K&M"],
    group: "clarinet",
  },
];

export const sample_tags_clar = [
  { name: "All", count: 6 },
  { name: "Mouthpiece", count: 2 },
  { name: "Crystal", count: 1 },
  { name: "Pomarico", count: 1 },
  { name: "BflatClarinet", count: 6 },
  { name: "AClarinet", count: 6 },
  { name: "Reed", count: 1 },
  { name: "Synthetic", count: 1 },
  { name: "Legere", count: 1 },
  { name: "Ligature", count: 2 },
  { name: "Silverstein", count: 1 },
  { name: "Ebonite", count: 2 },
  { name: "Vandoren", count: 2 },
  { name: "Stand", count: 1 },
  { name: "K&M", count: 1 },
];

export const saxophone_accesories = [
  {
    id: "1",
    url: "pic-1.jpg",
    name: "Stand Hercules 530BB",
    price: 200,
    fabrication: "US",
    tags: ["Stand", "Hercules", "AltoSax"],
    group: "saxophone",
  },
  {
    id: "2",
    url: "pic-2.jpg",
    name: "Legere Reed Signature Alto, Plastic 2",
    price: 30,
    fabrication: "US",
    tags: ["Reed", "Synthetic", "Legere", "AltoSax"],
    group: "saxophone",
  },
  {
    id: "3",
    url: "pic-3.jpg",
    name: "Otto Link 7 Metal Goldplated Mouthpiece",
    price: 80,
    fabrication: "US",
    tags: ["Mouthpiece", "Metal", "Otto", "AltoSax"],
    group: "saxophone",
  },
  {
    id: "4",
    url: "pic-4.jpg",
    name: "Francois Louis Ultimate Ligature -Alto",
    price: 100,
    fabrication: "US",
    tags: ["Ligature", "Louis", "AltoSax"],
    group: "saxophone",
  },
];

export const sample_tags_sax = [
  { name: "All", count: 4 },
  { name: "Mouthpiece", count: 1 },
  { name: "Otto", count: 1 },
  { name: "Metal", count: 1 },
  { name: "AltoSax", count: 4 },
  { name: "Reed", count: 1 },
  { name: "Synthetic", count: 1 },
  { name: "Legere", count: 1 },
  { name: "Ligature", count: 2 },
  { name: "Louis", count: 1 },
  { name: "Stand", count: 1 },
  { name: "Hercules", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
];
